- prod-devel-rcar.yaml
Add new parameter ENABLE_AOS_VIS to enable
closed source service aos-vis.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
> yaml: add a parameter to enable aos-vis

- prod-devel-rcar.yaml
Rename `h3ulcb-kf-4x2g` to `h3ulcb-4x2g-kf`.
Rename `h3ulcb-ab-4x2g` to `h3ulcb-4x2g-ab`.
This is done to comply with already used naming and to reflect
that `-kf` and `-ab` are based on `h3ulcb-4x2g` machine.
> yaml: Rename StarterKit-based machines

- prod-devel-rcar.yaml
This feature is required to enable VSP and build proper bl2 loader.
> yaml: Add 'multimedia' to MACHINE_FEATURES

- prod-devel-rcar.yaml
Github disables git:// protocol, so move to https://
Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
> yaml: fix github git protocols

- prod-devel-rcar.yaml
- Remove duplicated 'default' attribute
- Reorder list of variables for two machines, so
we have same order for all machines.
- Add comment regarding machine with 2x4g memory config
> yaml: Minor fixes in machine descriptors

- README.md
- prod-devel-rcar.yaml
ANDROID_PREBUILT_DDK=yes will trigger the system
to not fetch closed source graphics and use prebuilt
binaries. Assuming that all prebuilt should be placed
into eva directory in the root of the product.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
> doma: introduce options for prebuilt graphics

- README.md
- prod-devel-rcar.yaml
Archive with graphics prebuilds(rcar-prebuilts-graphics-xt-doma.tar.gz)
should be placed in the same directory as yaml file.
The contents of that archive will be unpacked to the android/eva.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
> yaml: add unpacking support for doma graphics prebuilds

- meta-aos-tune/recipes-aos/aos-vis/aos-vis_git.bbappend
- prod-devel-rcar.yaml
- yaml: Switch meta-aos to a new repository
- aos-vis: 'go' import has wrong path
> aos-vis related fixes

- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-h3-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-h3.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-m3-2x4g.cfg
Assignment of IP is performed by user space, therefore we have
no need to send DHCP requests during the start of the kernel.
Suggested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
---
This commit is copied from https://github.com/xen-troops/meta-xt-prod-devel/pull/375
> doma.cfg: Remove ip=dhcp from kernel command-line

- meta-xt-prod-devel-rcar-driver-domain/recipes-graphics/images/core-image-weston.bbappend
Sometimes we need some space for multimedia related tests,
so it's better to reserve it.
> domd: Reserve 500 MB of free space

- prod-devel-rcar.yaml
We do not need loaders (sa0, bl2, sa6, bl31) and tee in DomU.
> yaml: Do not build ATF and optee-os in DomU 

- prod-devel-rcar.yaml
`XT_PREBUILT_GSX_DIR` is used to define a folder with prebuilt
graphics binaries, and is propagated to `domd` and `domu` components.
> yaml: Add support for prebuilt graphics binaries

- README.md
- prod-devel-rcar.yaml
We support only StarterKit H3 ES3.0 8GB. And this machine is
described as `h3ulcb-4x2g` in our configuration.
This means that `h3ulcb` machine is for StarterKit H3 with 4GB.
But 4GB is supported only by ES2.0 SoC, which is not supported
by our product.
> Remove `h3ulcb` as not supported

- prod-devel-rcar.yaml
Name of config for Zephyr is defined by variable `XT_DOMZ_CONFIG_NAME`.
This variable should always be defined for proper parsing of `domz.bb`.
For now we do not use machine specific configs for domz, so
we can define variable just once. But it can't be empty.
Fixes a75c6408fe784ee666c6c75cd0e507190b4512ce
> yaml: Fix usage of domz.cfg

- prod-devel-rcar.yaml
Add layers with workaround for incorrect libc used by srec_cat.
See comments inside `meta-oe-fixups` for details.
---
This PR is complimentary to https://github.com/xen-troops/meta-xt-rcar/pull/33
> [Workaround] Use `meta-oe-fixups` to solve srecord issue

- meta-aos-tune/conf/layer.conf
- meta-xt-prod-devel-rcar-control/conf/layer.conf
- meta-xt-prod-devel-rcar-driver-domain/conf/layer.conf
To make sure that specific components can override/redefine settings from more generic levels, we set the following priorities for levels:
```
meta-xt-common     -  8
meta-xt-<platform> - 10
meta-xt-<product>  - 12
```
> Set priority of layers to 12

- meta-xt-domx-gen3/conf/layer.conf
- meta-xt-domx-gen3/recipes-extended/xen/xen-source.inc
- meta-xt-domx-gen3/recipes-extended/xen/xen-tools_git.bbappend
- meta-xt-domx-gen3/recipes-extended/xen/xen_git.bbappend
- prod-devel-rcar.yaml
For that purpose create a separate meta-xt-domx-gen3 sub-layer with appropriate xen/xen-tools recipes to perform v4.17 specific updates.
New Xen branch is at:
https://github.com/xen-troops/xen/commits/xen-4.17rc-migration
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
> dom0/domd: Migrate to new Xen v4.17

- prod-devel-rcar.yaml
- Added expect, ltrace, strace, evtest tools to the DomD & DomU
Motivation:
We need the above-mentioned set of the tools in order to:
- Automate communication with the target device ( expect )
- Debug the Linux input events ( evtest )
- Debug system calls of our applications ( strace )
- Debug shared library calls of our applicaitons ( ltrace )
Tested on h3ulcb-4x2g-kf machine.
Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>
> domd/domu: Install automation and debug applicaitons

- doc/u-boot-env.md
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-set-root
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-set-root
changes are mostly based on commit
65321202554d ("domd-set-root: expand boot options")
from meta-xt-prod-devel-rcar-gen4 repository
added changes to the ported commit:
- changed setting of static ip to dhcp option;
- moved property checks right after getting the property;
updated TFTP boot section inside u-boot-env.md:
- added description of how to set "nfs_server_ip", "my_ip"
and "nfs_dir" properties in a device tree via "tftp_dtb_load"
command;
Signed-off-by: Mykola Kvach <mykola_kvach@epam.com>
changes are mostly based on commit
82f3030bfe0b ("dom0: upgrade domu-set-root script")
from meta-xt-prod-devel-rcar-gen4 repository
added cosmetic changes to the ported commit:
- moved property checks right after getting the property;
updated TFTP boot section inside u-boot-env.md:
- added …
> domd-set-root: expand boot options

- prod-devel-rcar-agl.yaml
- prod-devel-rcar.yaml
We are moving to next Yocto release - Kirkstone. To preserve the current state of Xen Troops layers, we created "dunfell" branches before making transition to kirkstone. This is needed because not all products will be switched to kirkstone at once. It is expected that products that didn't made transition will use "dunfell" branch.
This patch goes into "dunfell" branch of meta-xt-prod-devel-rcar. It switches revisions from master to dunfell, so we can build dunfell-based version of prod-devel-rcar in case we need it.
> yaml: switch meta-xt-* layers to dunfell

- meta-xt-domx-gen3/recipes-graphics/wayland/weston-init.bbappend
weston-init: add specific ivi-shell settings
After the removal ivi-shell settings from meta-xt-common,
each product should provide its own settings with
respect to the needs.
> weston-init: add specific ivi-shell settings

- README.md
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/doma.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/backends.conf
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/displbe-backend.conf
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/sndbe-backend.conf
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/displbe-backend.conf
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/sndbe-backend.conf
- meta-xt-prod-devel-rcar-driver-domain/recipes-graphics/images/core-image-weston.bbappend
- prod-devel-rcar-agl.yaml
- prod-devel-rcar.yaml
In case of virtio functionality, we do not need installation of the
displbe and sndbe services. Driver domain should not install and
execute those services. Control domain should not have dependencies to
those services.
This patch is intended to introduce 'displbe' and 'sndbe' ditribution
features, which allow to turn mentioned services on and off for a
specific product.
We need a separate moulin parameter to implement builds with the virtio
devices sharing capabilities.
This patch adds first iteration of such a parameter. As of now, it does
only turn off the displbe and sndbe distro features.
It is much easier to navigate over the documentation, when it has table
of contents. This patch creates such a table in the README.md
> distro-features: Add displbe & sndbe

- meta-xt-prod-devel-rcar-control/recipes-guests/doma/doma.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-h3-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-m3-2x4g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/domd.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-h3ulcb-4x2g-ab.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-h3ulcb-4x2g-kf.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-h3ulcb-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-m3ulcb.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-x-h3-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-x-m3.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-xs-h3-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-xs-m3-2x4g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-xs-m3n.cfg
- prod-devel-rcar-agl.yaml
- prod-devel-rcar.yaml
Usually, in cases when Android is used, for 8 Gb RAM boards we assign 2Gb of RAM to DomD and 5Gb of RAM to DomA.
But if on top of that we are using virtio devices, we need to assign 3Gb of RAM to DomD and reduce amount of RAM on DomA to 4Gb. That is caused by a QEMU, which is running in the DomD to provide virtio backends. It requires additional RAM. Without this change QEMU will from time to time crash due to the insufficient amount of memory.
This patch is replacing statically defined RAM parameters in DomD and DomA Xen configuration files, and replaces them with the values, which are conditionally selected by Yocto. That is done using the OVERRIDES and MACHINEOVERRIDES mechanisms. Selected values are then injected into the installed doma.cfg and domd.cfg files.
> domd & doma: conditional Xen config RAM assignment

- prod-devel-rcar.yaml
There are some packages (like kmscube) which require libgles3. Imagination DDK actually provides support for this standard, but for some reason it was not advertised in recipes provided by Renesas. There is a patch to meta-xt-rcar that sets PROVIDE variable, and there we need to chose correct PREFERRED_PROVIDER in the same way as we did for libgles2.
> yaml: set PREFERRED_PROVIDER for virtual/libgles3

- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-m3ulcb.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-x-m3.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-xs-m3-2x4g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/files/domd-salvator-xs-m3n.cfg
- meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-xen.dts
- meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a7796-m3ulcb-xen.dts
- meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a77960-salvator-x-xen.dts
- meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a77961-salvator-xs-2x4g-xen.dts
Commit 30f9eb907d08 ("recipes-kernel: Update Linux for Renesas BSP v5.9.0") updated part of the device trees and recipes, but not all of them, so some of the boards was left in broken state. This commit finishes the work by updating the following boards:
- r8a77961-salvator-xs-2x4g (aka Salvator-XS M3W)
- r8a77960-salvator-x-m3 (aka Salvator-X M3N)
- r8a7796-m3ulcb (aka StarterKit Pro)
- r8a77951-h3ulcb (aka StarterKit Premiere)
Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
Fixes: 30f9eb907d08 ("recipes-kernel: Update Linux for Renesas BSP v5.9.0")
> recipes-kernel: finish updating for Renesas BSP v5.9.0

- meta-xt-domd-gen3/recipes-core/images/core-image-weston.bbappend
- meta-xt-domd-gen3/recipes-graphics/libsdl2/libsdl2_%.bbappend
- meta-xt-domd-gen3/recipes-qemu/qemu/qemu_%.bbappend
- meta-xt-domx-gen3/recipes-extended/xen/xen-source.inc
- prod-devel-rcar-agl.yaml
- prod-devel-rcar.yaml
xen & xen-tools: Switch to Xen 4.18
To use the virtio approach for sharing devices between the driver and the
guest Xen domains we need to switch to the Xen version 4.18. It contains
the required patches for the virtio use cases.
This patch switches to the usage of the xen-troops/xen of branch
xen-4.18-xt0.1, which is Xen of version 4.18 with additional xen-troops
patches on top of it, which were not yet upstreamed.
Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>
----
yaml: Fix wrong moulin syntax in build config
For 'yes' literal of the 'ENABLE_ANDROID' parameter, for dom0, there was
a 'conf' section, which was declared outside of the 'builder'. That lead
to doma.cfg with an empty memory parameter, which blocked the start of
the Android OS.
This patch fixes the error in …
> Integration of QEMU v7.0.0 + switching to the Xen 4.18

- meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
Build fails with the following error:
| install: cannot create regular file
'/home/lorc/work/builtbot-worker/meta-xt-prod-devel-rcar/build/yocto/ build-dom0/tmp/work/aarch64-poky-linux/domu/0.1-r0/image/etc/systemd/ system/domu.service.d': No such file or directory
This patch is intended to add installation of the systemd directory before making an attempt to install files into it.
> doma & domu: Add installation of the systemd directory

- meta-xt-prod-devel-rcar-control/recipes-guests/doma/doma.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-h3-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/doma/files/doma-generic-m3-2x4g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-generic-h3-4x2g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-generic-m3-2x4g.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-m3ulcb.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-salvator-x-m3.cfg
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-salvator-xs-m3n.cfg
Implement dynamic filling 'device_tree' parameter in xen configuration files for dom-u and dom-a depending on build configuration.
> dom-0: xen config 'device_tree' dynamic filling

- prod-devel-rcar.yaml
Add vendor_boot partition to use the original
Android u-boot for DomA.
> yaml: add vendor_boot partition for doma

- prod-devel-rcar.yaml
Some domain-specific things, like .dtb and .cfg are always used without any regard to the presence of corresponding domains. This commit wraps all domain-specific stuff under corresponding switches.
> yaml: wrap domain-specific variables under switches

- README.md
- meta-xt-prod-devel-rcar-control/recipes-guests/domd/domd.bbappend
When the prebuilt graphics package is chosen, the GPU passthrough (native mode) is used. So we don't need to force virt (host) mode in Linux driver.
> virtio: Do not run GSX driver in Host mode

- README.md
- prod-devel-rcar-agl.yaml
- prod-devel-rcar-virtio.yaml
- prod-devel-rcar.yaml
This commit replaces two options PREBUILT_DDK and ANDROID_PREBUILT_DDK with the single option GRAPHICS.
Possible options are 'binaries' and 'sources' that replace 'yes/no' for the previously used options PREBUILT_*.
Also, README.txt is updated accordingly, with two minor fixes not related to subject (missprint and new line at the end of the file).
> yaml: unite options related to prebuilt GFX (GSX) DDK

- meta-xt-domd-gen3/recipes-core/images/core-image-weston.bbappend
- meta-xt-domd-gen3/recipes-qemu/qemu/qemu_%.bbappend
- meta-xt-domd-gen3/recipes-tools/images/core-image-weston.bbappend
- meta-xt-domu-gen3/recipes-tools/images/core-image-weston.bbappend
- prod-devel-rcar-virtio.yaml
- prod-devel-rcar.yaml
- domu: install kmscube only when 3D GSX is used
- domd: domu: move utilities to the tools-related recipes
- virtio: wrap some wayland-related packages
> Rework some IMAGE_INSTALL

- meta-xt-domd-gen3/recipes-core/images/common_install.inc
- meta-xt-domd-gen3/recipes-core/images/core-image-minimal.bbappend
- meta-xt-domd-gen3/recipes-core/images/core-image-weston.bbappend
- meta-xt-domd-gen3/recipes-tools/images/common_install.inc
- meta-xt-domd-gen3/recipes-tools/images/core-image-minimal.bbappend
- meta-xt-domd-gen3/recipes-tools/images/core-image-weston.bbappend
- meta-xt-domu-gen3/recipes-tools/images/common_install.inc
- meta-xt-domu-gen3/recipes-tools/images/core-image-minimal.bbappend
- meta-xt-domu-gen3/recipes-tools/images/core-image-weston.bbappend
- meta-xt-prod-devel-rcar-driver-domain/recipes-graphics/images/common_install.inc
- meta-xt-prod-devel-rcar-driver-domain/recipes-graphics/images/core-image-minimal.bbappend
- meta-xt-prod-devel-rcar-driver-domain/recipes-graphics/images/core-image-weston.bbappend
This commit adds possibility to build our components inside core-image-minimal.
Parts that are common for core-image-minimal and core-image-weston are moved into the common_install.inc file.
> domd: domu: add support for core-image-minimal

- prod-devel-rcar-agl.yaml
- prod-devel-rcar-virtio.yaml
- prod-devel-rcar.yaml
Variables BUILD_TARGET_DOMD and BUILD_TARGET_DOMU are used to specify build target for corresponding domains and their build products.
This change allows to switch build target in further commits.
> yaml: use variable to specify `build_target`

- meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
- meta-xt-prod-devel-rcar-control/recipes-guests/domu/files/domu-vdevices-virtio-nogsx.cfg
- prod-devel-rcar-virtio.yaml
This commit adds possibility to use DomU without
any display and 3D GSX.
This is part of the preparation for the console-only set up.
> virtio: dom0: add 'no GPU, no display' config for DomU

- prod-devel-rcar-virtio.yaml
Switch to using HTTPS instead of SSH. This will allow users without GitHub registration to clone the repository.
> yaml: change meta-xt-vhost repository protocol

- meta-xt-domx-gen3/recipes-extended/xen/xen-source.inc
If the product overrides XEN_REL, it should override XEN_REV as well, because overridden branch may not contain revision defined in base layers.
So, considering that this is prod-devel, we set XEN_REV to ${AUTOREV}.
> xen: define SRCREV

- prod-devel-rcar-virtio.yaml
meta-xt-vhost contains only kernel patches and its content is merged into kernel on xen-troops branch that is used by the virtio setup. So can remove the meta-xt-vhost repo.
> domd: get rid of meta-xt-vhost

- meta-xt-domd-gen3/recipes-tools/images/common_install.inc
- meta-xt-domu-gen3/recipes-tools/images/common_install.inc
Lisot is the tools for virtio setup, so we should add it to the image only when 'enable_virtio' is in the DISTRO_FEATURES.
> domd: domu: wrap lisot by DISTRO_FEATURES

- meta-xt-domx-gen3/recipes-tools/lisot/lisot.bb
This commit aligns license related info with the actual license inside sources.
> Update the license for the lisot utility

- meta-xt-domx-gen3/recipes-tools/lisot/lisot.bb
We have moved the lisot repo to the xen-troops organization. So this commit updates SRC_URI accordingly.
> Change URL for the lisot sources

- meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
The variable `XT_DOMU_CONFIG_NAME` is not defined if domu is not used. In such a case, yocto fails during the parsing of the `domu.bbappend` file due to an attempt to calculate the checksum of the non-existing file `pvr-${XT_DOMU_CONFIG_NAME}`.
Fixes: 4c277f4f00095bb6875a1d82b51c63ef74704bbd ("dom-0: update xen config for dom-u")
> dom0: wrap usage of the XT_DOMU_CONFIG_NAME

- prod-devel-rcar-virtio.yaml
- prod-devel-rcar.yaml
This commit makes `binaries` as default value for the `--GRAPHICS` command-line option.
> yaml: change default config for GSX

- prod-devel-rcar-virtio.yaml
This layer doesn't exist and was skipped during the removal.
Fixes: 559c0d6c2f30 ("meta-aos-tune: remove unneeded meta-aos-tune layer")
---
The change was tested by the build.
> Remove not needed meta-aos-tune layer

- README.md
- Remove not supported machines from the list.
- Use default machine (h3ulcb-4x2g) in examples.
> README: update machines and examples

- doc/run_docker.sh
Option `-v` creates a directory, if specified host file was not found. As result if `run_docker.sh` will be used on the clean host without initialized `${HOME}/.gitconfig`, script will create a folder with the same name, resulting in mess.
But using of the `--mount type=bind,...` without the required file will result in error message that file doesn't exist. Thuis allowing user properly detect and solve an issue.
> docker: change the mounting of the .gitconfig

- prod-devel-rcar-virtio.yaml
- prod-devel-rcar.yaml
All common data should be kept inside the build folder.
> yaml: move common_data inside the build directory

- doc/Dockerfile
Do not use ~ in the PATH environment variable, since Docker will insert it without expansion, and
originally ~ is a bash function for
tilde expansion. Therefore, non-bash applications will not recognize that part of the PATH.
This patch also switches ENV to the original syntax.
> docker: fix PATH variable

- prod-devel-rcar-virtio.yaml
Fixes:0d95495bc197(doma: switch to Android 15)
The 0d95495bc197 commit points to the Android kernel manifest, which contains a mistake.
> doma: update kernel revision to correct

- doc/u-boot-env.md
We have to use `tee-raw.bin` instead of `tee.bin` for the flashing.
> doc: fix the name of the op-tee binary

- doc/u-boot-env.md
The u-boot variable `bootm_size` has to be empty during the boot.
Suggested-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
> doc: add info regarding bootm_size
